spring:
  application:
    name: "accounts"
  
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
    
  h2:
    console:
      enabled: true
      
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    
    hibernate:
      ddl-auto: update
    
    show-sql: true
  
  #config:
   # import:
    #- "application_qa.yml"
    #- "application_prod.yml"
    
  profiles:
    active: "prods"
  
  config:
    import: "optional:configserver:http://localhost:8071/" 
    
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: '*'
        
  health:
    readinessstate:
      enabled: true
    
    livenessstate:
      enabled: true
    probes:
      enabled: true


  endpoint:
    shutdown:
      enabled: true
      
      
  info:
    env:
      enabled: true
      
endpoints:
  shutdown:
    enabled: true

info:
  app:
    name: "accounts"
    description: "Eazy Bank Accounts Application"
    version: "1.0.0"  
    
    
eureka:
  instance:
    prefer-ip-address: true
  
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/     
      
logging:
  level:
    com:
      account: DEBUG
      


#build:
#  version: "3.0"
  
#accounts:
#  message: "Welcome to EazyBank accounts related local APIs "
#  contactDetails:
#    name: "John Doe - Developer"
#    email: "john@eazybank.com"
    
#  oncallsupport:
#    - (555) 555-1234
#    - (555) 523-1345
